export const GET_NEW_COMPLETE_REQUEST = 'GET_NEW_COMPLETE_REQUEST';
export const GET_NEW_COMPLETE_SUCESS = 'GET_NEW_COMPLETE_SUCESS';
export const GET_NEW_COMPLETE_FAIL = 'GET_NEW_COMPLETE_FAIL';

export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_REQUEST_SUCESS = 'GET_NEWS_REQUEST_SUCESS';
export const GET_NEWS_REQUEST_FAIL = 'GET_NEWS_REQUEST_FAIL';

export const GET_NEW_BY_TPYE_REQUEST = 'GET_NEW_BY_TPYE_REQUEST';
export const GET_NEW_BY_TPYE_SUCESS = 'GET_NEW_BY_TPYE_SUCESS';
export const GET_NEW_BY_TPYE_FAIL = 'GET_NEW_BY_TPYE_FAILT';   

export const NEW_LIKE_REQUEST = 'SET_NEW_LIKE_REQUEST';
export const NEW_LIKE_SUCESS = 'NEW_LIKE_SUCESS';
export const NEW_LIKE_FAIL = 'NEW_LIKE_FAIL';
export const NEW_LIKE_NOUSER = 'NEW_LIKE_NOUSER';

export const NEW_DISLIKE_REQUEST = 'NEW_DISLIKE_REQUEST';
export const NEW_DISLIKE_SUCESS = 'NEW_DISLIKE_SUCESS';
export const NEW_DISLIKE_FAIL = 'NEW_DISLIKE_FAIL';
export const NEW_DISLIKE_NOUSER = 'NEW_DISLOLE_NOUSER';

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST';
export const NEW_COMMENT_SUCESS = 'NEW_COMMENT_SUCESS';
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL';
export const NEW_COMMENT_NOUSER = 'NEW_COMMENT_NOUSER';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCESS = 'DELETE_COMMENT_SUCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCESS = 'UPDATE_COMMENT_SUCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';  

export const NEW_CREATE_REQUEST = 'NEW_CREATE_REQUEST';
export const NEW_CREATE_SUCESS = 'NEW_CREATE_SUCESS';
export const NEW_CREATE_FAIL = 'NEW_CREATE_FAIL';  

export const NEW_UPDATE_REQUEST = 'NEW_UPDATE_REQUEST';
export const NEW_UPDATE_SUCESS = 'NEW_UPDATE_SUCESS';
export const NEW_UPDATE_FAIL = 'NEW_UPDATE_FAIL';  

export const GET_HEADLINE_REQUEST = 'HEADLINE_REQUEST';
export const GET_HEADLINE_SUCESS = 'GET_HEADLINE_SUCESS';
export const GET_HEADLIME_FAIL = 'GET_HEADLIME_FAILT';  

export const GET_METRICS_REQUEST = 'GET_METRICS_REQUEST';
export const GET_METRICS_SUCESS = 'GET_METRICS_SUCESS';
export const GET_METRICS_FAIL = 'GET_METRICS_FAIL';