export const GET_NEW_COMPLETE_REQUEST = 'GET_NEW_COMPLETE_REQUEST';
export const GET_NEW_COMPLETE_SUCESS = 'GET_NEW_COMPLETE_SUCESS';
export const GET_NEW_COMPLETE_FAIL = 'GET_NEW_COMPLETE_FAIL';

export const GET_NEWS_REQUEST = 'GET_NEWS_REQUEST';
export const GET_NEWS_REQUEST_SUCESS = 'GET_NEWS_REQUEST_SUCESS';
export const GET_NEWS_REQUEST_FAIL = 'GET_NEWS_REQUEST_FAIL';