export const USER_LOGGED_APP = 'USER_LOGGED_APP';
export const USER_DELETE_ACOUNT = 'USER_DELETE_ACOUNT';
export const USER_IN_SESSION = 'USER_IN_SESSION';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SUCCESS_LOGOUT = 'USER_SUCCESS_LOGOUT';
export const USER_ERROR_LOGOUT = 'USER_ERROR_LOGOUT';
export const USER_ACTIONIN_NEWS = 'USER_ACTIONIN_NEWS';
export const USER_CONVERT_EDITOR = 'USER_CONVERT_EDITOR';